language: python
python: 2.7
sudo: false

# addons:
#   apt:
#     sources:
#       - deadsnakes
#     packages:
#       - python3.5
#       - python3.5-dev

install: pip install tox coverage coveralls

script:
  - tox
  # Coverage reporting is disabled for now since it conflicts with Hypothesis usage.
  # Combine all the coverage reports from the different tox envs:
  #- coverage combine
  #- coverage report --show-missing

#after_success:
#  - coveralls

notifications:
    email: false
