language: python
python: 2.7

env:
    - TOX_ENV=pypy
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py27-twisted-132
    - TOX_ENV=py27-twisted-trunk
    - TOX_ENV=py33-twisted-trunk
    - TOX_ENV=pyflakes
    - TOX_ENV=pyflakes3
    - TOX_ENV=sphinx

install: pip install tox

script: tox -e $TOX_ENV

notifications:
    email: false
